@startuml

title resolver.resolve_package 决策图

start
:输入 PackageConfig + DownloadDefaults;
:detect_runtime_arch();
if (package_format in {rpm, tar.gz}?) then (yes)
else (no)
  :raise ConfigError("Unsupported package format");
  stop
endif

if (filename_override 存在?) then (yes)
  :filename = filename_override;
else (no)
  :arch_token = arch_token_for_package(format, runtime_arch);
  if (format == tar.gz?) then (yes)
    :filename = product-artifact_version-arch_token.tar.gz;
  else (rpm)
    :filename = product-artifact_version\nrpm_arch_separator+arch_token.rpm;
  endif
endif

:base_url = build_project_base_url(download_defaults.base_url, version);
:package_url = base_url + '/' + filename;
:signature_url = package_url + signature_suffix;
:artifact_dir = product;
:package_path/signature_path = download_dir()/artifact_dir/...;
:输出 ResolvedPackage;
stop

@enduml
